# Model hyperparameters
model:
  use_performer: False
  image_size: 32
  patch_size: 4
  num_classes: 10
  model_depth: 4
  model_dim: 256
  mlp_dim: 256
  heads: 4
  dropout: 0.3
  kernel_fn: "ReLU"

# Training hyperparameters
train:
  batch_size: 512
  test_batch_size: 1000
  epochs: 200
  lr: 0.0005
  gamma: 0.7
  optimizer: "AdamW"
  weight_decay: 0.1
  scheduler: "CosineAnnealingLR"
  T_max: 200
  save_model: True

# Dataset settings
dataset:
  name: "CIFAR10"
  transform: 
    - type: "ToTensor"
    - type: "Normalize"
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]

# Wandb configuration
wandb:
  project: "vit-performer"
  use_wandb: true
  log_interval: 10
  dry_run: false

# Device settings
device:
  no_cuda: false
  no_mps: false
  seed: 1
