# Model hyperparameters
model:
  use_performer: True
  image_size: 256
  patch_size: 16
  num_classes: 365
  model_depth: 12
  model_dim: 768
  heads: 12
  dim_head: 64
  dropout: 0.1
  kernel_fn: "ReLU"

# Training hyperparameters
train:
  batch_size: 256
  test_batch_size: 128
  epochs: 90
  lr: 0.001
  gamma: 0.7
  optimizer: "AdamW"
  weight_decay: 0.03
  scheduler: "CosineAnnealingLR"
  T_max: 300
  save_model: True

# Dataset settings
dataset:
  name: "Places365"
  small: True
  transform: 
    - type: "Resize"
      size: [224, 224]
    - type: "ToTensor"
    - type: "Normalize"
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Wandb configuration
wandb:
  project: "vit-performer"
  use_wandb: true
  log_interval: 50
  dry_run: false

# Device settings
device:
  no_cuda: false
  no_mps: false
  seed: 1
